### ISSUE TITLE
Uncaught thread exception

### ISSUE THREAD

**Issue by HektorB** [adrigzr/badconga#8]
> Logger: root
> Source: custom_components/badconga/app/socket.py:28
> First occurred: 12:13:54 (1 occurrences)
> Last logged: 12:13:54
> Uncaught thread exception
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "/usr/local/lib/python3.8/threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "/config/custom_components/badconga/app/conga.py", line 51, in on_logout
>     self.loop()
>   File "/config/custom_components/badconga/app/conga.py", line 30, in loop
>     return self.client.login(self.email, self.password)
>   File "/config/custom_components/badconga/app/client.py", line 194, in login
>     self.socket.connect()
>   File "/config/custom_components/badconga/app/socket.py", line 28, in connect
>     self.sock.connect((self.host, self.port))
> TimeoutError: [Errno 110] Operation timed out
> 
I get that error from the Home Assistant log. My solution proposal is to catch that error and retry the connect call until the connection is successfully established.

**Comment by HektorB** [comment]
```
    def connect(self):
        """ connect """
        if not self.is_connected:
            logger.debug('connecting to %s:%s...', self.host, self.port)
            self.sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            self.sock.connect((self.host, self.port))
            self.is_connected = True
            self.thread = threading.Thread(target=self.handle)
            self.thread.start()
            self.trigger('connect')
```
I think this code block is generating the error. As far as I understand, the connection with the Cecotec backend is at some point interrupted and the system is not able to recover. 

According to the logs, the badconga thread retries to connect until the error of the previous log appears and all thread activity is stopped. 

The problem seems to be that the connect routing is creating the client socket and requesting the connection to the server. If this request fails, the previously created socket is not deleted. Then, when this method is called again, a new socket is created to be used in a new retry, but the previous one remains created.

[homeassistant_log.txt](https://github.com/adrigzr/badconga/files/5623072/homeassistant_log.txt)

**Comment by zzarne** [comment]
Should be fixed now with #18. It would be nice if you could report your model code (from the vacuum.conga entity) and model name after updating.
